More makefile changes in the src directory.  Also, MCUtils was missing, so I added it back in.
Compiler error conserning FastJet:

$(FASTJETDIR)/include/fastjet/PseudoJet.hh:266:7: error: subscripted value is neither array nor pointer
$(FASTJETDIR)/include/fastjet/PseudoJet.hh:266:7: error: subscripted value is neither array nor pointer
$(FASTJETDIR)/include/fastjet/PseudoJet.hh:266:7: error: subscripted value is neither array nor pointer
$(FASTJETDIR)/include/fastjet/PseudoJet.hh:266:7: error: subscripted value is neither array nor pointer

 Changes committed:
	new file:   ../include/MCUtils.hpp
	modified:   Makefile
	modified:   Makefile.common
	modified:   analyses/Makefile